require_relative("source/extensions/action_dispatch_http_headers_inspect")
require_relative("source/extensions/rails_console_account_access")
require_relative("source/extensions/paper_trail_record_trail_background")
require_relative("source/extensions/pundit_not_authorized_error_message")
require_relative("source/configuration")
